### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by okurina** [okurina/furima-39818#21]
# URL
https://furima-39818.onrender.com/

# Basic認証のIDとパスワード
・ID:user
・パスワード:1234

# 出品者用のメールアドレスとパスワード
・メールアドレス:furima@furima
・パスワード:123456abc

# 購入者用のメールアドレスとパスワード
・メールアドレス:test@test
・パスワード:123456abc

**Comment by moom1122** [comment]
@okurina さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **エラーハンドリングによって出品ページに戻った場合でも、入力済みの項目（商品画像・販売手数料・販売利益以外）は消えないこと**
エラーのたびに商品画像が消えてしまいます。


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by okurina** [comment]
確認ありがとうございます！

文面より、商品画像については消えてもよいという認識でした。
これは、商品名などと同じように消えないようにするべき、ということで相違ないでしょうか？
（見本アプリも商品画像は消えるようになっています…）

**Comment by moom1122** [comment]
@okurina さん、最終課題「FURIMA」の開発、お疲れ様です。

先程の修正依頼は、ご指摘の通り誤りです。大変申し訳ございません。
よって、ご提出いただいたアプリケーションについて、全て正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by okurina** [comment]
時間外にもかかわらず、ご確認いただきありがとうございました！
引き続きよろしくお願いいたします。
